### ISSUE TITLE
Crash when I start the game

### ISSUE THREAD

**Issue by davidii12** [BuiltBrokenModding/VoltzEngine#110]
Minecraft Version:
1.7.10
Forge Version:
10.13.4.1614-1.7.10
VoltzEngine Version:
1.9.14b302
*is this the latest curseforge build?*
**Please Pastebin crash**
---------------------
Crash Report:---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 5/19/21 11:31 AM
Description: Initializing game

java.lang.RuntimeException: Failed to process entry from file /content/icbm/deco/missile.small.json. Make corrections to the file or contact the file's creator for the issue to be fixed.
  Entry = block[{"name":"TileMissile","id":"TileMissile","tileEntity":{"id":"TileMissile","class":"com.builtbroken.icbm.content.display.TileEntityWrapperMissile"},"listeners":[{"id":"multiblock","layoutKey":"icbm:TileMissile"}],"subtypes":[{"meta":0},{"meta":1},{"meta":2}]}]
	at com.builtbroken.mc.framework.json.JsonContentLoader.process(JsonContentLoader.java:400)
	at com.builtbroken.mc.framework.json.JsonContentLoader.processEntries(JsonContentLoader.java:433)
	at com.builtbroken.mc.framework.json.JsonContentLoader.preInit(JsonContentLoader.java:176)
	at com.builtbroken.mc.framework.mod.loadable.LoadableHandler.load(LoadableHandler.java:144)
	at com.builtbroken.mc.framework.mod.loadable.LoadableHandler.preInit(LoadableHandler.java:100)
	at com.builtbroken.mc.seven.ModLoader.preInit(ModLoader.java:342)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.IllegalArgumentException: File is missing 'id' value from inside '{"meta":0}'
	at com.builtbroken.mc.framework.json.processors.JsonProcessor.ensureValuesExist(JsonProcessor.java:180)
	at com.builtbroken.mc.seven.framework.block.json.JsonBlockProcessor.readMeta(JsonBlockProcessor.java:168)
	at com.builtbroken.mc.seven.framework.block.json.JsonBlockProcessor.process(JsonBlockProcessor.java:132)
	at com.builtbroken.mc.framework.json.JsonContentLoader.process(JsonContentLoader.java:719)
	at com.builtbroken.mc.framework.json.JsonContentLoader.process(JsonContentLoader.java:353)
	... 41 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.builtbroken.mc.framework.json.JsonContentLoader.process(JsonContentLoader.java:400)
	at com.builtbroken.mc.framework.json.JsonContentLoader.processEntries(JsonContentLoader.java:433)
	at com.builtbroken.mc.framework.json.JsonContentLoader.preInit(JsonContentLoader.java:176)
	at com.builtbroken.mc.framework.mod.loadable.LoadableHandler.load(LoadableHandler.java:144)
	at com.builtbroken.mc.framework.mod.loadable.LoadableHandler.preInit(LoadableHandler.java:100)
	at com.builtbroken.mc.seven.ModLoader.preInit(ModLoader.java:342)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Linux (aarch64) version 4.9.179-perf+
	Java Version: 1.8.0-internal, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 229149600 bytes (218 MB) / 673710080 bytes (642 MB) up to 1212153856 bytes (1156 MB)
	JVM Flags: 2 total; -Xmx1300m -Xms128m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 Optifine OptiFine_1.7.10_HD_C1 81 mods loaded, 68 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCH	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCH	ivtoolkit{1.2.1} [IvToolkit] (minecraft.jar) 
	UCH	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
	UCH	voltzenginepreloader{0.0.1} [Voltz Engine Preloader] (minecraft.jar) 
	UCH	OpenModsCore{0.10.1} [OpenModsCore] (minecraft.jar) 
	UCH	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCH	FastCraft{1.25} [FastCraft] (fastcraft-1.25.jar) 
	UCH	divinerpg{1.4.1.5} [DivineRPG] ([1.7.10][SMP]DivineRPG-1.4.1.5.jar) 
	UCH	FLabsBF{4.3} [Better Furnaces] ([1.7.10]Better_Furnaces_V4.3.jar) 
	UCH	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UCH	adventurebackpack{1.7.10-0.8b} [Adventure Backpack] (adventurebackpack-1.7.10-0.8c.jar) 
	UCH	antiqueatlas{4.4.4} [Antique Atlas] (antiqueatlas-1.7.10-4.4.4.jar) 
	UCH	ArchimedesShips{1.7.10 v1.7.1} [Archimedes' Ships] (Archimedes-Ships-Mod-1.7.10.jar) 
	UCH	bettervillages{0.4} [Better Villages Mod] (Better-Villages-Mod-1.7.10.jar) 
	UCH	BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.1067-universal.jar) 
	UCH	chocolateQuest{1.0} [Chocolate Quest] (chocolateQuest-1.7.10-1.0.jar) 
	UCH	ChunkAnimator{@VERSION@} [Chunk Animator] (Chunk-Animator-Mod-1.7.10.jar) 
	UCH	CoFHCore{1.7.10R3.1.4} [CoFH Core] (CoFHCore-[1.7.10]3.1.4-329.jar) 
	UCH	craftnstar{0.2.1} [Craftable Nether Star +] (Craftable-Nether-Star-Mod-1.7.10.jar) 
	UCH	craftguide{1.6.8.2} [CraftGuide] (CraftGuide-Mod-1.7.10.jar) 
	UCH	lootablebodies{1.3.7} [DrCyano's Lootable Bodies] (CyanosLootableBodies-1.7.10-backport_1.3.7.jar) 
	UCH	doggytalents{1.14.2.317} [Doggy Talents] (DoggyTalents-1.7.10-1.14.2.317-universal.jar) 
	UCH	wizardry{1.1.5} [Electroblob's Wizardry] (Electroblob's+Wizardry+-+1.1.5+-+MC+1.7.10.jar) 
	UCH	eplus{3.0.2-d} [Enchanting Plus] (EnchantingPlus-1.7.10-3.0.2-d.jar) 
	UCH	Mantle{1.7.10-0.3.2.jenkins191} [Mantle] (Mantle-1.7.10-0.3.2b.jar) 
	UCH	MineFactoryReloaded{1.7.10R2.8.1} [MineFactory Reloaded] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UCH	ThermalFoundation{1.7.10R1.2.6} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.2.6-118.jar) 
	UCH	ThermalExpansion{1.7.10R4.1.5} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.1.5-248.jar) 
	UCH	TConstruct{1.7.10-1.8.8.build991} [Tinkers' Construct] (TConstruct-1.7.10-1.8.8.build991.jar) 
	UCH	GalacticraftCore{3.0.12} [Galacticraft Core] (GalacticraftCore-1.7-3.0.12.504.jar) 
	UCH	GalacticraftMars{3.0.12} [Galacticraft Planets] (Galacticraft-Planets-1.7-3.0.12.504.jar) 
	UCH	ExtraPlanets{1.7.10-1.9.5} [Extra Planets] (Extra-Planets-Mod-1.7.10.jar) 
	UCH	flansmod{4.5.1} [Flan's Mod] (Flans-Mod-1.7.10.jar) 
	UCH	FpsReducer{mc1.7.10-1.10.3} [FPS Reducer] (FPS-Reducer-Mod-1.7.10.jar) 
	UCH	grapplemod{1.7.10-v9} [Grappling hook mod] (grapplemod-1.7.10-v9.jar) 
	UCE	voltzengine{1.9.14.302} [Voltz Engine] (VoltzEngine-1.7.10-1.9.14b302.jar) 
	UCE	icbm{2.15.2.475} [ICBM] (ICBM-1.7.10-2.15.2b475.jar) 
	UCH	iChunUtil{4.2.2} [iChunUtil] (iChunUtil-4.2.2.jar) 
	UCH	IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar) 
	UCH	MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.1} [MFR Compat: ForgeMicroblock] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UCH	MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.1} [MFR Compat: Thermal Expansion] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UCH	MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.1} [MFR Compat: Tinkers' Construct] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UCH	MineFactoryReloaded|CompatVanilla{1.7.10R2.8.1} [MFR Compat: Vanilla] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UCH	minegicka3{1.0.0} [Minegicka 3] (Minegicka-3-Mod-1.7.10.jar) 
	UCH	me{1.3.1.2} [More Enchantments] (More-Enchantments-Mod-1.7.10.jar) 
	UCH	AencEx{0.0.1} [AencEx] (More-Enchantments-Mod-1.7.10.jar) 
	UCH	moreplayermodels{1.7.10b} [MorePlayerModels] (MorePlayerModels_1.7.10b.jar) 
	UCH	cfm{3.4.7} [�9MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.4.7(1.7.10).jar) 
	UCH	naturescompass{1.3.1} [Nature's Compass] (NaturesCompass-1.7.10-1.3.1.jar) 
	UCH	Neat{GRADLE:VERSION-GRADLE:BUILD} [Neat] (Neat+1.0-1.jar) 
	UCH	OpenMods{0.10.1} [OpenMods] (OpenModsLib-1.7.10-0.10.1.jar) 
	UCH	OpenBlocks{1.6} [OpenBlocks] (OpenBlocks-1.7.10-1.6.jar) 
	UCH	oreexcavation{1.1.134} [OreExcavation] (OreExcavation-1.1.134.jar) 
	UCH	PortalGun{4.0.0-beta-6} [PortalGun] (PortalGun-4.0.0-beta-6.jar) 
	UCH	primitivemobs{1.0} [Primitive Mobs] (primitivemobs-1.0c-1.7.2.jar) 
	UCH	progressiveautomation{1.6.35} [Progressive Automation] (ProgressiveAutomation-1.7.10-1.6.35.jar) 
	UCH	ReiMinimap{1.7.10} [Rei's Minimap] (Reis-Minimap-Mod-1.7.10.jar) 
	UCH	runicdungeons{1.1.6d} [Runic Dungeons] (runicdungeons-1.1.6d.jar) 
	UCH	territorychevsky{b12} [Territorial Dealings] (TerritorialDealings_1.7.10_b12.jar) 
	UCH	ThermalDynamics{1.7.10R1.2.1} [Thermal Dynamics] (ThermalDynamics-[1.7.10]1.2.1-172.jar) 
	UCH	trashslot{1.0.31} [TrashSlot] (trashslot-mc1.7.10-1.0.31.jar) 
	UCH	VillagersNose{1.3a} [Villager's Nose] (VillagersNose-1.7.10-1.3c.jar) 
	UCE	voltzenginemodcompat{1.9.14.302} [Voltz Engine Mod Compatibility Loader] (VoltzEngine-1.7.10-1.9.14b302.jar) 
	UCE	voltzenginemodflag{1.9.14.302} [VoltzEngine mod protection, flag, and region system] (VoltzEngine-1.7.10-1.9.14b302.jar) 
	UCH	waystones{1.0.12} [Waystones] (Waystones-mc1.7.10-1.0.12.jar) 
	UCH	yegamolchattels{1.1.2} [Ye Gamol Chattels] (YeGamolChattels-1.1.2.jar) 
	UD	MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.1} [MFR Compat: Applied Energistics] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UD	MineFactoryReloaded|CompatAtum{1.7.10R2.8.1} [MFR Compat: Atum] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UD	MineFactoryReloaded|CompatBackTools{1.7.10R2.8.1} [MFR Compat: BackTools] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UD	MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.1} [MFR Compat: BuildCraft] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UD	MineFactoryReloaded|CompatChococraft{1.7.10R2.8.1} [MFR Compat: Chococraft] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UD	MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.1} [MFR Compat: ExtraBiomes] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UD	MineFactoryReloaded|CompatForestry{1.7.10R2.8.1} [MFR Compat: Forestry] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UD	MineFactoryReloaded|CompatIC2{1.7.10R2.8.1} [MFR Compat: IC2] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UD	MineFactoryReloaded|CompatProjRed{1.7.10R2.8.1} [MFR Compat ProjectRed] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UD	MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.1} [MFR Compat: Railcraft] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UD	MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.1} [MFR Compat: Sufficient Biomes] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UD	MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.1} [MFR Compat: Thaumcraft] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UD	MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.1} [MFR Compat: TwilightForest] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	OpenModsLib class transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[player_damage_hook:FINISHED],[map_gen_fix:FINISHED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
	Class transformer null safety: all safe
	CoFHCore: -[1.7.10]3.1.4-329
	Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: optifine
	MineFactoryReloaded: -[1.7.10]2.8.1-174
	ThermalFoundation: -[1.7.10]1.2.6-118
	ThermalExpansion: -[1.7.10]4.1.5-248
	TConstruct Environment: Environment healthy.
	ThermalDynamics: -[1.7.10]1.2.1-172
	Stencil buffer state: Function set: ARB, pool: forge, bits: 8
	Launched Version: MCinaBox_0.1.4-p5
	LWJGL: 2.9.3
	OpenGL: GL4ES wrapper GL version 2.0 gl4es wrapper 1.1.2, ptitSeb
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because ARB_shader_objects, ARB_vertex_shader, and ARB_fragment_shader are supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)
----------
Explain issue in detail:
It crashed when I start the game

**Comment by davidii12** [comment]
Ok i somehow fixed it
