### ISSUE TITLE
Forge/VE crashes during modloading (MilitaryBaseDecor)

### ISSUE THREAD

**Issue by Hennamann** [BuiltBrokenModding/VoltzEngine#26]
When running MilitaryBaseDecor from Intellij IDEA, it crashed during modloading. It seems to be a specific problem to MilitaryBaseDecor as the error did not occur when running ICBM in the same way. 

```
---- Minecraft Crash Report ----
// Quite honestly, I wouldn't worry myself about that.

Time: 02.01.16 13:31
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.IllegalAccessError: tried to access field net.minecraft.item.Item.unlocalizedName from class com.builtbroken.mc.core.registry.ClientRegistryProxy
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:538)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243)
	at net.minecraft.client.Minecraft.startGame(Minecraft.java:522)
	at net.minecraft.client.Minecraft.run(Minecraft.java:942)
	at net.minecraft.client.main.Main.main(Main.java:164)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at net.minecraftforge.gradle.GradleStartCommon.launch(Unknown Source)
	at GradleStart.main(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: java.lang.IllegalAccessError: tried to access field net.minecraft.item.Item.unlocalizedName from class com.builtbroken.mc.core.registry.ClientRegistryProxy
	at com.builtbroken.mc.core.registry.ClientRegistryProxy.registerItem(ClientRegistryProxy.java:47)
	at com.builtbroken.mc.core.registry.ModManager.newItem(ModManager.java:343)
	at com.builtbroken.mc.core.Engine.preInit(Engine.java:393)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:535)
	... 17 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 667562080 bytes (636 MB) / 1037959168 bytes (989 MB) up to 1037959168 bytes (989 MB)
	JVM Flags: 3 total; -Xincgc -Xmx1024M -Xms1024M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.3.1428 15 mods loaded, 15 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	FML{7.10.99.99} [Forge Mod Loader] (forgeSrc-1.7.10-10.13.3.1428-1.7.10.jar) Unloaded->Constructed->Pre-initialized
	Forge{10.13.3.1428} [Minecraft Forge] (forgeSrc-1.7.10-10.13.3.1428-1.7.10.jar) Unloaded->Constructed->Pre-initialized
	NotEnoughItems{1.0.4.107} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.4.107-dev.jar) Unloaded->Constructed->Pre-initialized
	OpenComputers|Core{1.0.0} [OpenComputers (Core)] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	CodeChickenCore{1.0.6.44} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	Waila{1.5.11} [Waila] (Waila-1.5.11-RC1_1.7.10-dev.jar) Unloaded->Constructed->Pre-initialized
	Mantle{1.7.10-0.3.2.jenkins190} [Mantle] (Mantle-1.7.10-0.3.2.jenkins190-deobf.jar) Unloaded->Constructed->Pre-initialized
	TConstruct{1.7.10-1.8.7.build981} [Tinkers' Construct] (TConstruct-1.7.10-1.8.7.build981-deobf.jar) Unloaded->Constructed->Pre-initialized
	VoltzEngine{0.7.7.206} [VoltzEngine] (VoltzEngine-1.7.10-0.7.7b206-deobf-dev.jar) Unloaded->Constructed->Errored
	militarybasedecor{@MAJOR@.@MINOR@.@REVIS@.@BUILD@} [Military Base Decor] (MilitaryBaseDecor) Unloaded->Constructed->Errored
	ForgeMultipart{1.1.2.334} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.2.334-dev.jar) Unloaded->Constructed->Pre-initialized
	OpenComputers{1.4.0.242-dev} [OpenComputers] (OpenComputers-MC1.7.10-1.4.0.242-dev-dev.jar) Unloaded->Constructed->Pre-initialized
	McMultipart{1.1.2.334} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.1.2.334-dev.jar) Unloaded->Constructed->Pre-initialized
	ForgeMicroblock{1.1.2.334} [Forge Microblocks] (ForgeMultipart-1.7.10-1.1.2.334-dev.jar) Unloaded->Constructed->Pre-initialized
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 355.98' Renderer: 'GeForce GTX 760 (192-bit)/PCIe/SSE2'
	Mantle Environment: Environment healthy.
	TConstruct Environment: Environment healthy.
```

**Comment by Hennamann** [comment]
Actually i was wrong, the problem happens when running ICBM aswell. which leads me to believe that this could be a problem specific to my computer. Unsure of what could be causing it though...

**Comment by Hennamann** [comment]
I have now also tried reinstalling JRE, JDK, Scala and Gradle, and still getting the same error.

**Comment by aihema** [comment]
I'll forward it to the main dev

**Comment by dmodoomsirius** [comment]
I'll see if I can reproduce that error on my laptop when I get home.

**Comment by dmodoomsirius** [comment]
@Hennamann Can you also describe what version of gradle you are using? What version of idea you are using? What version of java you are using as well? all these will help me debug the scripts and see if its on the scripts end if not i can dig around to see why.

**Comment by DarkGuardsman** [comment]
You are running the voltz engine scripts as they contain access transformers. If those do not run correctly then you may get this kind of error.

**Comment by Hennamann** [comment]
@dmodoomsirius Running Gradle 2.7, Java 1.8_65, Intellij Idea 15.

@DarkGuardsman How would i go about running those scripts properly?

**Comment by Hennamann** [comment]
Found a temporary solution by adding the VE_at.cfg access transformer into resources and then referencing it in the build.gradle file. I obviously won't push that, but it serves as a solution until we figure out why forge doesen't load the VE access transformer from the deobfuscated jar file.

**Comment by dmodoomsirius** [comment]
I'll take a look asap. Might be something I can do with gradle.

**Comment by DarkGuardsman** [comment]
Its because he is using the deobf version @dmodoomsirius . From what I've been told forge does not apply access transformers at compile time. It will do it at run time but that doesn't help. What I suggest is adding the access transformers to the mod in question. This is the solution I use to fix issues with ICBM and similiar mods.

That being said you should just setup a VoltzEngine workspace and add VE mods as modules. This way you can adjust VE code as needed. As well pull any changes I make to VE that are not backwards compatible.

**Comment by dmodoomsirius** [comment]
I will try to fix that before i update the scripts.

**Comment by dmodoomsirius** [comment]
2:09 PM <dmod> hey AbrarSyed with fg 1.2 how come its not recognizing the at in the deobf jar?
2:10 PM <@AbrarSyed> thats new to FG 2
2:10 PM <dmod> https://github.com/BuiltBrokenModding/VoltzEngine/issues/26 is what im referencing to
2:12 PM <dmod> is there a way for it to recognize the at in fg 1.2?
2:12 PM <@AbrarSyed> out it in src/api/resources

**Comment by dmodoomsirius** [comment]
I might use gradle's download plugin to dl the at and put it in the right spot. just need to test to make sure i get it right. @Hennamann I will let you know when i do have a update on this again.

**Comment by dmodoomsirius** [comment]
I will also make sure gradle verify's it more then likely. As well as have it overwrite if the source is newer.

**Comment by Hennamann** [comment]
I'l try setting up MBD as a module and see how it works, if i like it i might switch to it, if not i'l just wait for @dmodoomsirius to fix it with gradle.
