### ISSUE TITLE
Nosuchmethoderror crash on startup

### ISSUE THREAD

**Issue by robthegray** [BuiltBrokenModding/VoltzEngine#27]
when I start mc 1.7.10 the client crashes while loading generating the following crash report

[sfxworks] Edit: Excerpts for Author 
Notes for author:
VoltzEngine{0.7.2.188} Voltz Engine Unloaded->Constructed->Pre-initialized->Initialized->Errored
Caused by: java.lang.NoSuchMethodError: 
...
at com.builtbroken.mc.lib.mod.compat.tinkers.TinkerProxy.postInit(TinkerProxy.java:49)

```
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 1/2/16 2:35 PM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoSuchMethodError: net.minecraftforge.oredict.OreDictionary.getOres(Ljava/lang/String;Z)Ljava/util/List;
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:162)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:695)
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:288)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:541)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoSuchMethodError: net.minecraftforge.oredict.OreDictionary.getOres(Ljava/lang/String;Z)Ljava/util/List;
	**at com.builtbroken.mc.lib.mod.compat.tinkers.TinkerProxy.postInit(TinkerProxy.java:49)**
	at com.builtbroken.mc.lib.mod.loadable.LoadableHandler.postInit(LoadableHandler.java:139)
	at com.builtbroken.mc.core.Engine.postInit(Engine.java:516)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:694)
	... 10 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.7.0_72, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3537794320 bytes (3373 MB) / 5368709120 bytes (5120 MB) up to 5368709120 bytes (5120 MB)
	Mod Pack: Unknown / None
	LiteLoader Mods: 2 loaded mod(s)
          - VoxelLib version 2.3.1
          - VoxelMap version 1.2.3
	LaunchWrapper: 47 active transformer(s)
          - Transformer: cpw.mods.fml.common.asm.transformers.PatchingTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.MarkerTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.SideTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.EventSubscriptionTransformer
          - Transformer: codechicken.lib.asm.ClassHeirachyManager
          - Transformer: codechicken.core.asm.InterfaceDependancyTransformer
          - Transformer: codechicken.core.asm.TweakTransformer
          - Transformer: codechicken.core.asm.DelegatedTransformer
          - Transformer: codechicken.core.asm.DefaultImplementationTransformer
          - Transformer: mrtjp.relocation.asm.Transformer
          - Transformer: invtweaks.forge.asm.ContainerTransformer
          - Transformer: mariculture.fishery.VanillaOverride
          - Transformer: codechicken.nei.asm.NEITransformer
          - Transformer: com.mumfrey.liteloader.transformers.event.EventProxyTransformer
          - Transformer: com.mumfrey.liteloader.launch.LiteLoaderTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.CrashReportTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.DeobfuscationTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.AccessTransformer
          - Transformer: net.minecraftforge.transformers.ForgeAccessTransformer
          - Transformer: codechicken.core.asm.CodeChickenAccessTransformer
          - Transformer: cofh.asm.CoFHAccessTransformer
          - Transformer: invtweaks.forge.asm.ITAccessTransformer
          - Transformer: mariculture.core.AccessTransformers
          - Transformer: cpw.mods.fml.common.asm.transformers.ModAccessTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ItemStackTransformer
          - Transformer: cofh.asm.CoFHClassTransformer
          - Transformer: Reika.DragonAPI.ASM.InterfaceInjector
          - Transformer: Reika.DragonAPI.ASM.APIStripper
          - Transformer: Reika.DragonAPI.ASM.DragonAPIClassTransfomer
          - Transformer: Reika.DragonAPI.ASM.FMLItemBlockPatch
          - Transformer: Reika.DragonAPI.ASM.DependentMethodStripper
          - Transformer: Reika.LegacyCraft.LegacyASMHandler$LegacyTransformer
          - Transformer: Reika.RotaryCraft.Auxiliary.RotaryASMHandler$ASMExecutor
          - Transformer: Reika.RotaryCraft.Auxiliary.RotaryASMHandler$InterfaceVerifier
          - Transformer: cpw.mods.fml.common.asm.transformers.TerminalTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.LiteLoaderEventInjectionTransformer
          - Transformer: com.thevoxelbox.common.TimeUpdateTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.LiteLoaderCallbackInjectionTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.JoinGamePacketTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.ServerChatPacketTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.LoginSuccessPacketTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.ChatPacketTransformer
          - Transformer: com.thevoxelbox.voxelmap.litemod.VoxelMapTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.ServerCustomPayloadPacketTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.CustomPayloadPacketTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.MinecraftOverlayTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ModAPITransformer
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms5120m -Xmx5120m -XX:MaxPermSize=256m -XX:+UseG1GC -XX:MaxGCPauseMillis=4
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.85.1291 Minecraft Forge 10.13.2.1291 102 mods loaded, 102 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	FML{7.10.85.1291} [Forge Mod Loader] (modpack.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	Forge{10.13.2.1291} [Minecraft Forge] (modpack.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	CodeChickenCore{1.0.4.29} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	MCVanillaTweaks{1.0} [Mariculture - Vanilla Tweaks] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	NotEnoughItems{1.0.4.83} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.4.83-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	voltzenginepreloader{0.0.1} [Voltz Engine Preloader] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	<DragonAPI ASM>{0} [DragonAPI ASM Data Initialization] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	LookingGlass{0.2.0.00} [Looking Glass] (lookingglass-1.7.10-0.2.0.00.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	securitycraft{v1.8.0.6-beta} [SecurityCraft] ([1.7.10] SecurityCraft 1.8.0.6-beta.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	AncientWarfare{2.4.113-beta-MC1.7.10} [Ancient Warfare Core] (ancientwarfare-2.4.113-beta-MC1.7.10-FULL.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	CoFHCore{1.7.10R3.0.2} [CoFH Core] (CoFHCore-[1.7.10]3.0.2-262.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	BuildCraft|Core{6.3.1} [BuildCraft] (buildcraft-6.3.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	AncientWarfareAutomation{2.4.113-beta-MC1.7.10} [Ancient Warfare Automation] (ancientwarfare-2.4.113-beta-MC1.7.10-FULL.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	AncientWarfareNEIPlugin{2.4.113-beta-MC1.7.10} [Ancient Warfare NEI Plugin] (ancientwarfare-2.4.113-beta-MC1.7.10-FULL.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	AncientWarfareNpc{2.4.113-beta-MC1.7.10} [Ancient Warfare NPCs] (ancientwarfare-2.4.113-beta-MC1.7.10-FULL.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	AncientWarfareStructure{2.4.113-beta-MC1.7.10} [Ancient Warfare Structures] (ancientwarfare-2.4.113-beta-MC1.7.10-FULL.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	BiblioCraft{1.9.2} [BiblioCraft] (BiblioCraft[v1.9.2][MC1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	ThermalFoundation{1.7.10R1.0.0} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.0.0-81.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	ThermalExpansion{1.7.10R4.0.1} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.0.1-182.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	BigReactors{0.4.1A2} [Big Reactors] (BigReactors-0.4.1A2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	BuildCraft|Transport{6.3.1} [BC Transport] (buildcraft-6.3.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	BuildCraft|Silicon{6.3.1} [BC Silicon] (buildcraft-6.3.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	BuildCraft|Builders{6.3.1} [BC Builders] (buildcraft-6.3.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	BuildCraft|Energy{6.3.1} [BC Energy] (buildcraft-6.3.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	BuildCraft|Factory{6.3.1} [BC Factory] (buildcraft-6.3.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	CarpentersBlocks{3.3.4.2} [Carpenter's Blocks] (Carpenter's Blocks v3.3.4.2 - MC 1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	ChickenChunks{1.3.4.16} [ChickenChunks] (ChickenChunks-1.7.10-1.3.4.16-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	IC2{2.2.660-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.660-experimental.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	Railcraft{9.7.0.0} [Railcraft] (Railcraft_1.7.10-9.7.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	chisel{2.4.1.40} [Chisel 2] (Chisel2-2.4.1.40.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	ctmlib{1.0.1.5} [CTMLib] (Chisel2-2.4.1.40.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	ComputerCraft{1.74} [ComputerCraft] (ComputerCraft1.74.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	CopiousDogs{${mcversion}-${version}} [Copious Dogs] (copious-dogs-1.7.10-1.1.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	customnpcs{1.7.10c} [CustomNpcs] (CustomNPCs_1.7.10c.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	props{1.11} [Decocraft] (Decocraft-v1.11_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	MrTJPCoreMod{1.1.0.31} [MrTJPCore] (MrTJPCore-1.1.0.31-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	ProjRed|Core{4.7.0pre8.92} [ProjectRed Core] (ProjectRed-1.7.10-4.7.0pre8.92-Base.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	Waila{1.5.8} [Waila] (Waila-1.5.9_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	TConstruct{1.7.10-1.8.3-RFNerf.DEV.1911337} [Tinkers' Construct] (TConstruct-1.7.10-1.8.3-RFNerf.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	DragonAPI{1.0} [DragonAPI] (DragonAPI 1.7.10 V7f.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	Enchiridion{1.1} [Enchiridion] (Enchiridion-1.7.X-1.2b.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	ExtraTiC{1.4.5} [ExtraTiC] (ExtraTiC-1.7.10-1.4.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	flansmod{4.10.0} [Flan's Mod] (Flans Mod-1.7.10-4.10.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	funkylocomotion{1.0} [Funky Locomotion] (funky-locomotion-1.7.10-beta-7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	gvc{0.4.0} [Gliby's Voice Chat Mod] (gliby.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	GregsLighting{1.11.2} [Greg's Lighting] (GregsLighting-1.11.2-mc1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	IC2NuclearControl{2.0.8c} [Nuclear Control 2] (IC2NuclearControl-2.0.8c.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	instatower{1.5.6} [InstaTower] (instatower-1.7.10-1.5.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	inventorytweaks{1.58-147-645ca10} [Inventory Tweaks] (inventorytweaks-1.58-147.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	mod_LATL{1.9} [Lamps and Traffic lights] (LATL.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	LegacyCraft{1.0} [LegacyCraft] (LegacyCraft 1.7.10 V7a.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	LifeMMOBlocks{172b} [LifeMMOBlocks] (lmomaterials.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	TeNNoX_KeyAndCodeLock{1.4} [KeyAndCodeLock] (Locks.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	Mariculture{1.7.10-1.2.4.2a} [Mariculture] (Mariculture-Deluxe-1.7.10-1.2.4.2a.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	MariTech{1.0} [Marine Technlogy] (Mariculture-Deluxe-1.7.10-1.2.4.2a.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	radixcore{1.3.4} [RadixCore] (RadixCore-1.7.10-1.3.4-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	mca{4.1.5} [Minecraft Comes Alive] (MCA-1.7.10-4.1.5-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	mcheli{0.10.7} [MC Helicopter] (mcheli) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	Mekanism{7.1.1} [Mekanism] (Mekanism-1.7.10-7.1.1.127.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	MekanismGenerators{7.1.1} [MekanismGenerators] (MekanismGenerators-1.7.10-7.1.1.127.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	MekanismTools{7.1.1} [MekanismTools] (MekanismTools-1.7.10-7.1.1.127.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	MineMenu{1.2.0} [MineMenu] (MineMenu-1.7.10-1.2.0.B44-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	cfm{3.4.7} [§9MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.4.7(1.7.10).jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	NEIAddons{1.12.2.9} [NEI Addons] (neiaddons-mc1710-1.12.2.9.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	NEIAddons|Botany{1.12.2.9} [NEI Addons: Botany] (neiaddons-mc1710-1.12.2.9.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	NEIAddons|Forestry{1.12.2.9} [NEI Addons: Forestry] (neiaddons-mc1710-1.12.2.9.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	NEIAddons|CraftingTables{1.12.2.9} [NEI Addons: Crafting Tables] (neiaddons-mc1710-1.12.2.9.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	NEIAddons|ExNihilo{1.12.2.9} [NEI Addons: Ex Nihilo] (neiaddons-mc1710-1.12.2.9.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	NEIPlugins{1.1.0.10-unofficial} [NEI Plugins Unofficial] (NEIPlugins-MC1.7.10-1.1.0.10-unofficial.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	Pistronics2{0.5.1} [Pistronics 2] (Pistronics2-v0.5.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	PneumaticCraft{1.6.6-68} [PneumaticCraft] (PneumaticCraft-1.7.10-1.6.6-68-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	ProjRed|Transmission{4.7.0pre8.92} [ProjectRed Transmission] (ProjectRed-1.7.10-4.7.0pre8.92-Integration.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	ProjRed|Transportation{4.7.0pre8.92} [ProjectRed Transportation] (ProjectRed-1.7.10-4.7.0pre8.92-Mechanical.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	ProjRed|Exploration{4.7.0pre8.92} [ProjectRed Exploration] (ProjectRed-1.7.10-4.7.0pre8.92-World.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	ProjRed|Compatibility{4.7.0pre8.92} [ProjectRed Compatibility] (ProjectRed-1.7.10-4.7.0pre8.92-Compat.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	ProjRed|Integration{4.7.0pre8.92} [ProjectRed Integration] (ProjectRed-1.7.10-4.7.0pre8.92-Integration.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	ProjRed|Fabrication{4.7.0pre8.92} [ProjectRed Fabrication] (ProjectRed-1.7.10-4.7.0pre8.92-Fabrication.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	ProjRed|Illumination{4.7.0pre8.92} [ProjectRed Illumination] (ProjectRed-1.7.10-4.7.0pre8.92-Lighting.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	ProjRed|Expansion{4.7.0pre8.92} [ProjectRed Expansion] (ProjectRed-1.7.10-4.7.0pre8.92-Mechanical.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	rowam{5.2.2} [Rails of War Automation Module] (Rails of War Automation Module-5.2.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	RotaryCraft{1.0} [RotaryCraft] (RotaryCraft 1.7.10 V7f.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	ReactorCraft{1.0} [ReactorCraft] (ReactorCraft 1.7.10 V7f.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	mod_RoadWorks{2.0} [Roadworks] (roads.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	row{1.7.10-15.01.18-2} [Rails of War] (RoW-1.7.10-15.01.18-2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	simplefluidtanks{1.7.10-1.2.0.5} [Simple Fluid Tanks] (simplefluidtanks-1.7.10-1.2.0.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	ThermalDynamics{1.7.10R1.0.0RC7} [Thermal Dynamics] (ThermalDynamics-[1.7.10]1.0.0RC7-98.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	TiCTooltips{1.2.4} [TiC Tooltips] (TiCTooltips-mc1.7.10-1.2.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	TMechworks{1.7.10-67.34d1d9b} [Tinkers' Mechworks] (TMechworks_mc1.7.10_0.2.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	**VoltzEngine{0.7.2.188} [Voltz Engine] (VoltzEngine-1.7.10-0.7.2b188-dev-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Errored**
	WailaHarvestability{1.1.0} [Waila Harvestability] (WailaHarvestability-mc1.7.x-1.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	WR-CBE|Core{1.4.1.9} [WR-CBE Core] (WR-CBE-1.7.10-1.4.1.9-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	WR-CBE|Addons{1.4.1.9} [WR-CBE Addons] (WR-CBE-1.7.10-1.4.1.9-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	WR-CBE|Logic{1.4.1.9} [WR-CBE Logic] (WR-CBE-1.7.10-1.4.1.9-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	ForgeRelocation{0.0.1.4} [ForgeRelocation] (ForgeRelocation-0.0.1.4-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	MCFrames{1.0} [MCFrames] (ForgeRelocation-0.0.1.4-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	RelocationFMP{0.0.1.2} [RelocationFMP] (ForgeRelocationFMP-0.0.1.2-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	CoFHCore: -[1.7.10]3.0.2-262
	ThermalFoundation: -[1.7.10]1.0.0-81
	ThermalExpansion: -[1.7.10]4.0.1-182
	Mantle Environment: Environment healthy.
	TConstruct Environment: Environment healthy.
	ThermalDynamics: -[1.7.10]1.0.0RC7-98
```

**Comment by robthegray** [comment]
this occurs when voltz engine is installed

**Comment by robthegray** [comment]
I know it has to do with Tcon but I've no idea how to fix it

**Comment by robthegray** [comment]
without removing Tcon anyways

**Comment by robthegray** [comment]
also, I don't think this is very closely related to the gear issue from earlier

**Comment by DarkGuardsman** [comment]
cpw.mods.fml.common.LoaderException: java.lang.NoSuchMethodError: net.minecraftforge.oredict.OreDictionary.getOres(Ljava/lang/String;Z)Ljava/util/List;

From what I can tell the code can't find the OreDictionary which is part of forge.

**Comment by robthegray** [comment]
oh, I see

**Comment by DarkGuardsman** [comment]
Try updating your forge version; VE is compiled against 1428 and your using 1291.

**Comment by robthegray** [comment]
ok
