### ISSUE TITLE
EE3/Voltz/ICBM compatibility issue?

### ISSUE THREAD

**Issue by border999** [BuiltBrokenModding/VoltzEngine#35]
#Minecraft Version:1.7.10
Forge Version:1.7.10-Forge10.13.4.1614-1.7.10
VoltzEngine Version:VoltzEngine-1.7.10-0.15.10b158-dev-universal
---------------------
http://pastebin.com/E3Ga2Dr8
----------
Explain issue in detail: When trying to  log into my world after updating to my current version of ICBM and Voltz I crash. It would appear that EE3 doesn't like this version. Seemed that piece was left out of the crash report for some reason.

**Comment by DarkGuardsman** [comment]
Not sure how you know its EE, from that crash its just Forge's packet handler failing. Plus you have a ton of mods in there and have not tested with just EE, ICBM, and VE. That being said I'll do a local test here shortly too see if there is an issue. To be honest its most likely just a faulty packet sender causing the issue.

**Comment by DarkGuardsman** [comment]
So far through testing I can not replicate the issue, I am doing a backtrace through the errored section. This way I can see if it is even used by VoltzEngine as I have a theory it is not.

**Comment by border999** [comment]
I will attempt to start again and look for any new information.

**Comment by border999** [comment]
http://pastebin.com/T3CuCtRL
here's the full log

**Comment by border999** [comment]
or at least what was there

**Comment by DarkGuardsman** [comment]
The crash is on EE's side, I'll look into it more but it will need to be fixed on their side. Not sure what the update would have caused the issue. Knowing how EE works it could be failing to process some of VE or ICBM's items. Which would still need to be fixed on their side as I don't use or mess with their APIs. 

[11:02:26] [Server thread/ERROR] [FML]: HandshakeCompletionHandler exception
java.lang.NullPointerException
    at com.pahimar.ee3.exchange.EnergyValueRegistry.serialize(EnergyValueRegistry.java:804) ~[EnergyValueRegistry.class:?]
    at com.pahimar.ee3.exchange.EnergyValueRegistry.serialize(EnergyValueRegistry.java:27) ~[EnergyValueRegistry.class:?]
    at com.google.gson.TreeTypeAdapter.write(TreeTypeAdapter.java:70) ~[TreeTypeAdapter.class:?]
    at com.google.gson.Gson.toJson(Gson.java:593) ~[Gson.class:?]
    at com.google.gson.Gson.toJson(Gson.java:572) ~[Gson.class:?]
    at com.google.gson.Gson.toJson(Gson.java:527) ~[Gson.class:?]
    at com.google.gson.Gson.toJson(Gson.java:507) ~[Gson.class:?]
    at com.pahimar.ee3.exchange.EnergyValueRegistry.toJson(EnergyValueRegistry.java:766) ~[EnergyValueRegistry.class:?]
    at com.pahimar.ee3.network.message.MessageSyncEnergyValues.<init>(MessageSyncEnergyValues.java:30) ~[MessageSyncEnergyValues.class:?]
    at com.pahimar.ee3.handler.PlayerEventHandler.onPlayerLoggedIn(PlayerEventHandler.java:50) ~[PlayerEventHandler.class:?]
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_1113_PlayerEventHandler_onPlayerLoggedIn_PlayerLoggedInEvent.invoke(.dynamic) ~[?:?]
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:?]
    at cpw.mods.fml.common.FMLCommonHandler.firePlayerLoggedIn(FMLCommonHandler.java:550) ~[FMLCommonHandler.class:?]

**Comment by pahimar** [comment]
Delete your energy value json or set it to constantly regen. Its got a null reference in it for an item that no longer exists under its original registered name.

**Comment by DarkGuardsman** [comment]
@pahimar Ty, was about to come bug you after I ate dinner, but you beat me to it :)

**Comment by border999** [comment]
Thanks, thought this might have been something world breaking.
