### ISSUE TITLE
Server crashed after Clay Furnace placed

### ISSUE THREAD

**Issue by ams2990** [BuiltBrokenModding/VoltzEngine#8]
I recognize that is a MadScience block listed in the title, but the stack trace shows the problem is in VoltzEngine.

	java.lang.NoSuchMethodError: net.minecraft.util.MathHelper.func_154353_e(D)I
        at com.builtbroken.mc.prefab.tile.Tile.determineOrientation(Tile.java:1095) ~[Tile.class:1.7.10-0.3.3b16]
        at com.builtbroken.mc.prefab.tile.Tile.determineForgeDirection(Tile.java:1119) ~[Tile.class:1.7.10-0.3.3b16]
        at com.builtbroken.mc.prefab.tile.TileMachine.onPlaced(TileMachine.java:27) ~[TileMachine.class:1.7.10-0.3.3b16]
        at com.builtbroken.mc.prefab.tile.BlockTile.func_149689_a(BlockTile.java:112) ~[BlockTile.class:1.7.10-0.3.3b16]
        at net.minecraft.item.ItemBlock.placeBlockAt(ItemBlock.java:213) ~[abh.class:?]
        at net.minecraft.item.ItemBlock.func_77648_a(ItemBlock.java:103) ~[abh.class:?]
        at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:528) ~[ForgeHooks.class:git-Cauldron-Reloaded-1.7.10-1.1343.01.0]
        at net.minecraft.item.ItemStack.func_77943_a(ItemStack.java:147) ~[add.class:?]
        at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:489) ~[mx.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:861) ~[nh.class:?]
        at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60) ~[jo.class:?]
        at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9) ~[jo.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244) ~[ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) ~[nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:980) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:430) ~[lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_40]

**Comment by DarkGuardsman** [comment]
Sometimes I facepalm at why

``` java
   @SideOnly(Side.CLIENT)
    public static int func_154353_e(double p_154353_0_)
    {
        return (int)(p_154353_0_ >= 0.0D ? p_154353_0_ : -p_154353_0_ + 1.0D);
    }
```

is client side only when it uses no client only code. I'll fix it shortly and yes it is a Voltz Engine bug.

**Comment by ams2990** [comment]
lol.
