### ISSUE TITLE
java.lang.RuntimeException: Failed to load resources from class path.  Class='class com.builtbroken.mc.seven.ModLoader' folder= '/content/voltzengine/'

### ISSUE THREAD

**Issue by setsunafseiei** [BuiltBrokenModding/VoltzEngine#96]
Minecraft Version:
- 1.7.10
Forge Version:
- 10.13.4.1614
VoltzEngine Version:
- 1.9.9b242
*is this the latest curseforge build?*
YES
**Please Pastebin crash**
https://pastebin.com/BnE2ftZz
```
---------------------
Crash Report:
---- Minecraft Crash Report ----
// Would you like a cupcake?

Time: 11/3/17 12:26 PM
Description: Initializing game

java.lang.RuntimeException: Failed to load resources from class path.  Class='class com.builtbroken.mc.seven.ModLoader' folder= '/content/voltzengine/'
	at com.builtbroken.mc.framework.json.JsonContentLoader.loadResourcesFromPackage(JsonContentLoader.java:767)
	at com.builtbroken.mc.framework.json.JsonContentLoader.loadResources(JsonContentLoader.java:465)
	at com.builtbroken.mc.framework.json.JsonContentLoader.preInit(JsonContentLoader.java:152)
	at com.builtbroken.mc.framework.mod.loadable.LoadableHandler.load(LoadableHandler.java:144)
	at com.builtbroken.mc.framework.mod.loadable.LoadableHandler.preInit(LoadableHandler.java:100)
	at com.builtbroken.mc.seven.ModLoader.preInit(ModLoader.java:333)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.RuntimeException: Failed to walk files from URI = jar:file:/H:/Minecraft/Modpack/%5B1.7.10-Forge%5D%20Automation/mods/VoltzEngine-1.7.10-1.9.9b242.jar!/content/voltzengine/
	at com.builtbroken.mc.framework.json.JsonContentLoader.loadResourcesFromPackage(JsonContentLoader.java:801)
	at com.builtbroken.mc.framework.json.JsonContentLoader.loadResourcesFromPackage(JsonContentLoader.java:758)
	... 41 more
Caused by: java.lang.IllegalArgumentException: Illegal character in path at index 27: file:/H:/Minecraft/Modpack/[1.7.10-Forge]%20Automation/mods/VoltzEngine-1.7.10-1.9.9b242.jar
	at com.sun.nio.zipfs.ZipFileSystemProvider.uriToPath(ZipFileSystemProvider.java:87)
	at com.sun.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:107)
	at java.nio.file.FileSystems.newFileSystem(Unknown Source)
	at com.builtbroken.mc.framework.json.JsonContentLoader.loadResourcesFromPackage(JsonContentLoader.java:789)
	... 42 more
Caused by: java.net.URISyntaxException: Illegal character in path at index 27: file:/H:/Minecraft/Modpack/[1.7.10-Forge]%20Automation/mods/VoltzEngine-1.7.10-1.9.9b242.jar
	at java.net.URI$Parser.fail(Unknown Source)
	at java.net.URI$Parser.checkChars(Unknown Source)
	at java.net.URI$Parser.parseHierarchical(Unknown Source)
	at java.net.URI$Parser.parse(Unknown Source)
	at java.net.URI.<init>(Unknown Source)
	at com.sun.nio.zipfs.ZipFileSystemProvider.uriToPath(ZipFileSystemProvider.java:85)
	... 45 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.builtbroken.mc.framework.json.JsonContentLoader.loadResourcesFromPackage(JsonContentLoader.java:767)
	at com.builtbroken.mc.framework.json.JsonContentLoader.loadResources(JsonContentLoader.java:465)
	at com.builtbroken.mc.framework.json.JsonContentLoader.preInit(JsonContentLoader.java:152)
	at com.builtbroken.mc.framework.mod.loadable.LoadableHandler.load(LoadableHandler.java:144)
	at com.builtbroken.mc.framework.mod.loadable.LoadableHandler.preInit(LoadableHandler.java:100)
	at com.builtbroken.mc.seven.ModLoader.preInit(ModLoader.java:333)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_60, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1852773864 bytes (1766 MB) / 2068840448 bytes (1973 MB) up to 4205838336 bytes (4011 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -Xms2G -Xmn256M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1558 15 mods loaded, 15 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1558-1.7.10.jar) 
	UCH	Forge{10.13.4.1558} [Minecraft Forge] (forge-1.7.10-10.13.4.1558-1.7.10.jar) 
	UCH	voltzenginepreloader{0.0.1} [Voltz Engine Preloader] (minecraft.jar) 
	UCE	voltzengine{1.9.9.242} [Voltz Engine] (VoltzEngine-1.7.10-1.9.9b242.jar) 
	UCE	icbm{2.15.2.475} [ICBM] (ICBM-1.7.10-2.15.2b475.jar) 
	UCE	voltzenginemodcompat{1.9.9.242} [Voltz Engine Mod Compatibility Loader] (VoltzEngine-1.7.10-1.9.9b242.jar) 
	UCE	voltzenginemodflag{1.9.9.242} [VoltzEngine mod protection, flag, and region system] (VoltzEngine-1.7.10-1.9.9b242.jar) 
	UCH	ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCH	McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCH	ForgeRelocation{0.0.1.4} [ForgeRelocation] (ForgeRelocation-0.0.1.4-universal.jar) 
	UCH	MCFrames{1.0} [MCFrames] (ForgeRelocation-0.0.1.4-universal.jar) 
	UCH	RelocationFMP{0.0.1.2} [RelocationFMP] (ForgeRelocationFMP-0.0.1.2-universal.jar) 
	UCH	MrTJPCoreMod{1.1.0.33} [MrTJPCore] (MrTJPCore-1.1.0.33-universal.jar) 
	UCH	ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 388.00' Renderer: 'GeForce GTX 1050/PCIe/SSE2'
	Launched Version: 1.7.10-Forge10.13.4.1558-1.7.10
	LWJGL: 2.9.1
	OpenGL: GeForce GTX 1050/PCIe/SSE2 GL version 4.6.0 NVIDIA 388.00, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)
----------
```
Explain issue in detail:
Cannot initialize Voltz Engine

**Comment by DarkGuardsman** [comment]
Looks like the main issue is
`Caused by: java.net.URISyntaxException: Illegal character in path at index 27: file:/H:/Minecraft/Modpack/[1.7.10-Forge]%20Automation/mods/VoltzEngine-1.7.10-1.9.9b242.jar`

index 27 is '['

Which most likely means the java URI system is not happy with []. A temp solution is to rename the folder to remove [] as well spaces '%20' part is a space ' '. This should allow it to load correctly while I work on a fix.

**Comment by TheTonyy** [comment]
i have a similar problem. Client runs fine but the server crashes. I am using Voltz engine version 1.9.14b302 for minecraft 1.7.10
`Illegal character in path at index 19: file:/E:/Minecraft/[SERVER]%201.7.10%20modded/mods/VoltzEngine-1.7.10-1.9.14b302.jar`

**Comment by DarkGuardsman** [comment]
Same suggestion remove [] and it should work. Seems java's URI and URL system do not like those characters. Currently rewriting the JSON loader code to no longer use URI but will be a while. As it seems there is no simple solution to loading files from .jars other than URI mixed with file system.

**Comment by DarkGuardsman** [comment]
Give this file a try and see if it solves the issue https://minecraft.curseforge.com/projects/voltz-engine/files/2498663

**Comment by TheTonyy** [comment]
Thankyou! Its working fine now.
