### ISSUE TITLE
Crash with Underground Biomes Construct: duplicated unlocalized name?

### ISSUE THREAD

**Issue by LemADEC** [BuiltBrokenModding/VoltzEngine#97]
Minecraft Version:
- 1.7.10
Forge Version:
- Forge10.13.4.1614
VoltzEngine Version:
- VoltzEngine-1.7.10-1.9.14b303
Crash Report:
```
cpw.mods.fml.common.LoaderException: java.lang.IllegalArgumentException: The name UndergroundBiomes:igneous_voltzengine:${metaLocalization} has been registered twice, for exterminatorJeff.undergroundBiomes.common.block.BlockUBMetadataOre@421c9314 and exterminatorJeff.undergroundBiomes.common.block.BlockUBMetadataOre@6df719a0.
	at cpw.mods.fml.common.registry.GameRegistry.registerBlock(GameRegistry.java:239)
	at cpw.mods.fml.common.registry.GameRegistry.registerBlock(GameRegistry.java:188)
	at exterminatorJeff.undergroundBiomes.worldGen.OreUBifier.registerBlockWithMetadata(OreUBifier.java:142)
	at exterminatorJeff.undergroundBiomes.worldGen.OreUBifier.setupUBOre(OreUBifier.java:96)
	at exterminatorJeff.undergroundBiomes.worldGen.OreUBifier.setupUBOre(OreUBifier.java:90)
	at exterminatorJeff.undergroundBiomes.common.UndergroundBiomes.registerCrossModOres(UndergroundBiomes.java:418)
	at exterminatorJeff.undergroundBiomes.common.UndergroundBiomes.load(UndergroundBiomes.java:448)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:737)
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.IllegalArgumentException: The name UndergroundBiomes:igneous_voltzengine:${metaLocalization} has been registered twice, for exterminatorJeff.undergroundBiomes.common.block.BlockUBMetadataOre@421c9314 and exterminatorJeff.undergroundBiomes.common.block.BlockUBMetadataOre@6df719a0.
	at cpw.mods.fml.common.registry.FMLControlledNamespacedRegistry.add(FMLControlledNamespacedRegistry.java:389)
	at cpw.mods.fml.common.registry.GameData.registerBlock(GameData.java:894)
	at cpw.mods.fml.common.registry.GameData.registerBlock(GameData.java:869)
	at cpw.mods.fml.common.registry.GameRegistry.registerBlock(GameRegistry.java:229)
	... 42 more
```
Explain issue in detail:
Crash when starting the game

UBC is known to use unlocalized names as registry ids.
I appears VE doesn't format them properly.

Issue wasn't reproduced with VoltzEngine-1.7.10-1.7.1b143

**Comment by DarkGuardsman** [comment]
Was this confirmed to be solved?

**Comment by LemADEC** [comment]
Not reproduced with VoltzEngine-1.7.10-1.9.18b389
